name: Format python code
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@master
        with:
          find: "@borg.on"
          replace: "@friday.on"
      - name: Create Pull Request
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'handler fix'
          commit_options: '--no-verify'
          repository: .
          commit_user_name: starkgang
          commit_user_email: starkgangz@gmail.com
          commit_author: starkgang <starkgangz@gmail.comm>
